"""E6: observar → interpretar → investigar → validar → apresentar evidências."""
S=[]
def slide(key,title,sub,cards=(),note='',takeaway='',kind='cards',code=None,section='Fundamentos',**extra):
 d=dict(id=key,title=title,sub=sub,cards=list(cards),note=note,takeaway=takeaway,kind=kind,code=code,section=section,role='conceito',question='',answer='',study_only=False)
 d.update(extra);S.append(d);return d
def table(key,title,sub,headers,rows,note,takeaway,section='Fundamentos',widths=None,**extra):
 return slide(key,title,sub,note=note,takeaway=takeaway,kind='table',headers=headers,rows=rows,widths=widths or [1/len(headers)]*len(headers),section=section,**extra)
def flow(key,title,sub,nodes,note,takeaway,section='Fundamentos',**extra):
 return slide(key,title,sub,note=note,takeaway=takeaway,kind='flow',nodes=nodes,section=section,**extra)
def checkpoint(key,title,questions,answers,section):
 slide(key,'Verificação | '+title,'Depois dos conceitos e exemplos • explique a evidência',[(f'{i+1}. Situação',q) for i,q in enumerate(questions)],'Peça respostas breves apoiadas nos exemplos anteriores. Revele o gabarito depois de ouvir justificativas. Se houver confusão, volte à figura ou ao cálculo pertinente. As verificações são formativas e de discussão em grupo, sem criar nota individual ou alterar os pesos oficiais.','O próximo slide traz as três respostas explicadas.',section=section,role='pergunta',questions=questions)
 slide(key+'_resposta','Respostas comentadas | '+title,'Gabarito • do conceito à decisão',[(f'{i+1}. Resposta',a) for i,a in enumerate(answers)],'\n\n'.join(f'Pergunta: {q}\nResposta: {a}' for q,a in zip(questions,answers)),'Diferencie o que foi observado, o que é hipótese e o que foi confirmado.',section=section,role='resposta',answers=answers,answers_for=key)

slide('percurso','Fechar o ciclo: da entrega à evidência','Encontro 6 • observabilidade, diagnóstico e apresentação final',[
 ('Retomar','E4: executar e integrar.\nE5: entregar e recuperar.\nE6: observar o efeito da mudança.'),('Compreender','Logs, métricas e traces.\nIndicadores, objetivos e alertas.\nIncidente com causa comprovada.'),('Demonstrar','Instrumentação mínima.\nRelatório do incidente.\nApresentação do mesmo projeto da equipe.')],
 'Comece pela experiência do usuário, não pela lista de ferramentas. A equipe já tem aplicação, pipeline, containerização e plano de entrega. Hoje precisa explicar o que aconteceu na execução, como soube e o que fez com essa informação. O projeto não muda, e a API do professor é apenas uma demonstração. A apresentação final tem cinco a sete minutos e usa evidências do repositório, sem uma entrega paralela fora dele.',
 'Uma entrega só gera aprendizado quando seu comportamento pode ser observado e explicado.')
slide('agenda','Quatro horas com espaço para as apresentações','Planejamento para até sete equipes • ajustar ao número real de grupos',[
 ('0–80 min | Base','0–10: contexto.\n10–40: sinais e instrumentação.\n40–60: SLI/SLO e alertas.\n60–80: diagnóstico de incidente.'),('80–180 min | Aplicar','80–95: intervalo.\n95–125: demo guiada.\n125–145: IA e revisão.\n145–180: preparação das equipes.'),('180–240 min | Fechar','180–236: até 7 blocos de 8 min.\nCada fala: 5–7 min.\n236–240: síntese e submissão final.')],
 'São 240 minutos, com 15 de intervalo, 35 de preparação e 56 reservados às apresentações. Cada bloco de oito minutos inclui a fala de cinco a sete e o restante para feedback ou transição. Com menos equipes, devolva o tempo à preparação ou ao feedback. O número de sete blocos acomoda a faixa usual de vinte a trinta estudantes em grupos de quatro a cinco; não é uma nova regra de formação. Se a turma tiver mais grupos, replaneje a exposição antes da aula, preservando o tempo oficial de cada fala.',
 'O último encontro precisa de tempo para observar, preparar evidências e apresentar; não apenas exposição.')
flow('user_path','Comece pelo caminho que o usuário percorre','Exemplo conhecido: consultar o contador de visitas', [('Cliente','GET /visitas\nEspera resposta correta'),('API','Recebe e processa\nConsulta a dependência'),('Banco','Lê o contador\nResponde à consulta'),('Cliente','Recebe status e corpo\nPercebe tempo e resultado')],
 'Trace a operação do ponto de vista de quem a utiliza. Um processo vivo ou uma conexão SQL isolada não comprovam que o resultado final chegou corretamente. Na demonstração, o cliente mede o tempo total da chamada e a API mede a parte executada no servidor. Os valores podem diferir por incluir etapas diferentes. Esse mapa orienta onde instrumentar e qual dado procurar quando o usuário relata erro ou lentidão.',
 'Observe uma operação relevante; CPU baixa ou container Up não provam que ela funciona.')
slide('monitoring','Monitoramento e observabilidade: capacidades próximas','Medir o conhecido e investigar o comportamento do sistema',[
 ('Monitorar','Acompanhar condições escolhidas.\nEx.: erro e duração de uma rota.\nDetectar desvio de um critério.'),('Investigar','Combinar sinais e contexto.\nExplorar uma falha ainda não prevista.\nFormular e testar hipóteses.'),('Instrumentar','Emitir dados úteis no código.\nPreservar versão, tempo e contexto.\nColetar e consultar os sinais.')],
 'Evite apresentar monitoramento e observabilidade como produtos rivais. As capacidades se sobrepõem: um painel pode revelar um problema e uma investigação pode usar o mesmo dado com outra pergunta. Instalar um dashboard não cria observabilidade automaticamente. É preciso emitir sinais pertinentes, coletá-los e interpretá-los. No projeto pequeno, um log estruturado, uma medição definida e um teste funcional já apoiam uma investigação concreta.',
 'Ferramenta organiza dados; a instrumentação e o contrato da aplicação dão significado a eles.')
table('signals','Logs, métricas e traces: três perspectivas','Cada sinal responde melhor a um tipo de pergunta', ['Sinal','O que representa','Exemplo'],[
 ['Log','Registro de um evento com contexto.','Requisição terminou com 503 e código de erro.'],['Métrica','Medição agregada ao longo do tempo.','5 falhas em 20 requisições.'],['Trace','Caminho e duração de operações correlacionadas.','API aguardou uma chamada à dependência.']],
 'Uma linha de log descreve um evento; a métrica permite comparar volume ou distribuição; o trace relaciona operações de uma execução. Eles não são os únicos sinais possíveis, nem é obrigatório implantar os três em todo projeto. O laboratório gera logs e métricas; traces serão explicados por um diagrama conceitual. Não chamaremos um request_id isolado de tracing distribuído. A escolha deve seguir o que a equipe precisa investigar.',
 'Combine perspectivas; não espere que um único sinal prove sozinho toda a causa.',widths=[.18,.40,.42])
slide('log_example','Log estruturado: campos que apoiam o diagnóstico','Exemplo ilustrativo com valores fictícios • JSON facilita consulta',[
 ('Contexto','timestamp: quando.\nversion: qual código.\nrequest_id: qual chamada.'),('Resultado','route e status: operação e resposta.\nduration_ms: tempo no servidor.\nerror_code: pista da falha.')],
 'Leia os campos na ordem da investigação. A hora situa o evento, versão liga ao release, rota define a operação e request_id permite localizar o mesmo atendimento. O exemplo não deve ser copiado como resultado real da equipe. A duração da API mede do recebimento até preparar a resposta; não inclui toda a rede do cliente. O log não inclui senha, corpo enviado ou query string. Um error_code é evidência a interpretar, não diagnóstico final sem contexto.',
 'Um log útil permite localizar o evento sem expor dados que a investigação não precisa.',kind='code',code='{"timestamp":"2026-09-26T12:00:00Z",\n "service":"api-visitas",\n "version":"3.0.0-observabilidade",\n "request_id":"exemplo-123",\n "method":"GET", "route":"/visitas",\n "status":503, "duration_ms":12.4,\n "error_code":"ECONNREFUSED"}')
slide('log_privacy','O que registrar — e o que não precisa ir para o log','Utilidade, retenção e acesso fazem parte do desenho',[
 ('Registrar','Evento, hora e serviço.\nRota normalizada, status e duração.\nVersão e identificador de correlação.'),('Evitar','Senha, token e cabeçalho de autorização.\nPayload completo sem necessidade.\nDados pessoais e URLs sensíveis.'),('Controlar','Quem consulta e por quanto tempo.\nVolume e nível dos eventos.\nSeparar produção de dados fictícios.')],
 'Um dump de environment ou request completo pode vazar informação. Níveis info, warn e error ajudam a filtrar, mas precisam de uma convenção coerente. Um aviso não é automaticamente um incidente; um evento info pode mostrar uma mudança importante. IDs também podem permitir correlação com pessoas, dependendo do sistema, então não assuma que todo identificador é irrelevante para privacidade. Para a aula, use requisições e registros fictícios e apenas os campos necessários.',
 'Mais texto não significa mais evidência; selecione contexto que ajude a responder a uma pergunta.')
flow('correlation','Identificação da requisição: ligar resposta e evento','No laboratório a API gera X-Request-Id para cada chamada', [('Resposta HTTP','Cabeçalho com o ID\nCopiar o valor observado'),('Log da API','Mesmo request_id\nStatus, versão e duração'),('Investigação','Localizar aquele evento\nComparar com outros sinais')],
 'Demonstre curl -i para obter o cabeçalho e depois procure o ID exato no log. A API gera um UUID, sem confiar em um valor arbitrário do cliente. Isso permite correlacionar o atendimento local. Um trace distribuído ainda exige propagar contexto entre serviços e registrar spans relacionados. O identificador não deve ser usado como label de métrica, pois criaria uma série por requisição. Mostre essa distinção antes de introduzir histogramas e traces.',
 'request_id é uma chave de correlação; sozinho não descreve o caminho distribuído.')
table('metric_types','Tipos de métrica: conte, meça e distribua','Escolher o tipo evita interpretações erradas', ['Tipo','Comportamento','Exemplo'],[
 ['Counter','Acumula eventos; pode zerar na reinicialização.','Total de respostas 503.'],['Gauge','Valor que pode subir e descer.','Memória usada ou fila atual.'],['Histograma','Conta observações em faixas de valores.','Duração das requisições.']],
 'Counter não é a quantidade de requisições por segundo: é o total acumulado desde uma referência. Para taxa, compare a variação e o intervalo, considerando reinícios. Gauge representa um estado atual, como tamanho de fila. Histograma organiza uma distribuição; no formato clássico do Prometheus as faixas são cumulativas. O laboratório expõe counters e histograma em memória; docker stats oferece uma observação de recursos, sem histórico por si só.',
 'Diga sempre o nome, a unidade, a população e o intervalo da medição.',widths=[.22,.43,.35])
table('counter_example','De contador a taxa: exemplo resolvido','Mesma instância, sem reinício entre as duas leituras', ['Observação','Cálculo e interpretação'],[
 ['12:00:00 → total 100','Primeira leitura do counter.'],['12:00:10 → total 140','Foram concluídas 40 requisições no intervalo.'],['Taxa média','(140 − 100) / 10 s = 4 requisições/s.'],['Se o valor caiu para 3','Pode ter ocorrido reset; não calcular uma taxa negativa.']],
 'Faça a subtração no quadro antes de usar uma função de consulta. O exemplo exige a mesma série e um intervalo definido. Um reset por reinício da API muda a referência do contador; sistemas de consulta podem tratar isso, mas duas leituras soltas não reconstroem todos os eventos perdidos. Agregar contadores de instâncias sem separar resets também exige cuidado. Não confunda requisições por segundo com latência em segundos por requisição.',
 'Counter é total; taxa é variação por tempo; reinícios mudam como a variação deve ser interpretada.',widths=[.36,.64])
slide('latency','Média e percentil mostram coisas diferentes','Exemplo sintético: 100 requisições ordenadas por duração',note=
 'A distribuição tem 95 valores de 20 ms, quatro de 200 ms e um de 2000 ms. A média é (95×20 + 4×200 + 1×2000)/100 = 47 ms. Pelo método nearest-rank, p95 é o 95º valor, 20 ms, e p99 é o 99º, 200 ms. A requisição de dois segundos fica além do p99 neste conjunto. Métodos de percentil e estimativas por buckets podem diferir. Explique a população e a janela; não transforme uma amostra curta numa garantia para o mês.',
 takeaway='Uma média baixa pode conviver com requisições lentas; percentil também depende da amostra e do método.',kind='latency')
slide('traces','Trace: visualizar a duração e a relação entre operações','Diagrama conceitual • valores ilustrativos, não capturados no laboratório',note=
 'Um trace reúne spans ligados por contexto. Um span representa uma operação com início, fim e atributos; o vínculo pai-filho ajuda a reconstruir a execução. No desenho a API dura 120 ms e a chamada ao banco ocupa parte desse intervalo, 80 ms. Não some duração do span pai com a do filho: os intervalos se sobrepõem. Operações paralelas também impedem somas ingênuas. Um trace amostrado conta a história daquele atendimento, não garante cobertura de todas as chamadas.',
 takeaway='Spans mostram relações e intervalos; duração maior sugere onde investigar, não prova a causa sozinha.',kind='trace')
flow('telemetry','Do código ao painel: como a telemetria chega à consulta','Separar instrumentação, transporte, armazenamento e uso', [('Emitir','Aplicação registra\nLogs, medidas ou spans'),('Coletar','Agente/coletor obtém\nProcessa e encaminha'),('Armazenar','Backend indexa\nMantém histórico'),('Usar','Consultar e visualizar\nAlertar e investigar')],
 'OpenTelemetry fornece padrões e componentes para instrumentar, coletar e exportar; não é, por si só, o banco que armazena todos os dados nem o dashboard final. Prometheus pode coletar métricas por scraping; ferramentas de visualização consultam fontes configuradas. A demonstração mínima lê logs pelo Docker e consulta o endpoint de métricas e uma sonda Python. Não vamos fingir que essa combinação já tem retenção centralizada, tracing ou alta disponibilidade de observabilidade.',
 'O dado precisa chegar à consulta com contexto; emitir um endpoint não cria automaticamente histórico.')
table('tools','Ferramentas: reconhecer a responsabilidade de cada uma','Exemplos de componentes • nenhuma plataforma paga é exigida', ['Componente','Papel típico','Na aula'],[
 ['Logs do Docker','Acessar a saída emitida pelo processo.','Usado na demonstração.'],['Prometheus','Coletar e consultar séries de métricas.','Formato de exposição e consulta conceitual.'],['Grafana','Visualizar dados de fontes configuradas.','Exemplo de finalidade de dashboard.'],['OpenTelemetry / Jaeger','Instrumentar/exportar; analisar traces, respectivamente.','Conceitos e diagrama.']],
 'Não trate ferramentas como uma lista de instalação obrigatória. Docker logs não produz logs que a aplicação não emitiu. Grafana depende de uma fonte e de consultas corretas. Um coletor pode encaminhar sinais para backends distintos. O projeto deve demonstrar observabilidade mínima com ferramentas compatíveis com seu contexto. O laboratório não instala Prometheus, Grafana ou Jaeger; evita consumir o tempo das apresentações com infraestrutura adicional.',
 'Comece pela pergunta operacional; depois escolha como emitir, guardar e consultar o sinal.',widths=[.27,.43,.30])
checkpoint('signals_check','Interpretar os sinais',[
 'O counter está em 500. Isso significa 500 requisições por segundo?', 'Uma chamada tem request_id no log. Já temos um trace distribuído completo?', 'A média é 47 ms. Podemos afirmar que ninguém esperou dois segundos?'],[
 'Não. É um total acumulado. Para taxa, calcule variação por tempo e trate resets.', 'Não. Correlação local não substitui spans e propagação de contexto entre operações e serviços.', 'Não. A média pode esconder cauda lenta; no exemplo há uma chamada de 2000 ms.'], 'Fundamentos')

slide('sli_contract','SLI: definir exatamente o que será medido','Indicador de nível de serviço ligado a uma experiência do usuário',[
 ('População','GET /visitas elegíveis.\nJanela declarada.\nOrigem da observação identificada.'),('Evento bom','Status 200 e total inteiro válido.\nFalha de conexão também importa na visão do cliente.'),('Indicador','Chamadas boas / chamadas elegíveis.\nReportar volume e resultado.\nSem chamadas: sem amostra.')],
 'A sonda do laboratório verifica status e conteúdo; uma métrica do servidor baseada apenas em HTTP 200 não observa exatamente o mesmo contrato. Requisições que não chegam à API não aparecem em seu counter. Por isso declare o ponto de observação. Excluir healthchecks evita que chamadas automáticas verdes diluam a falha da operação de negócio. Zero tráfego não prova sucesso de 100%; é ausência de amostra para esse cálculo.',
 'Um SLI é útil quando população, sucesso, janela e origem estão definidos.',section='Confiabilidade')
table('sli_calc','SLI calculado: explicação passo a passo','Exemplo fictício de uma janela já encerrada', ['Dado','Cálculo / significado'],[
 ['Elegíveis','1000 chamadas de GET /visitas.'],['Boas','992 retornaram o contrato esperado.'],['Falhas','1000 − 992 = 8 chamadas não boas.'],['SLI de sucesso','992 / 1000 × 100 = 99,2%.']],
 'Use números pequenos o suficiente para que todos acompanhem. As oito falhas podem incluir status de erro, corpo inválido ou falta de resposta, desde que a coleta do indicador consiga observar esses casos. Não misture consultas administrativas no denominador nem selecione somente os logs bem-sucedidos. A janela terminou; o cálculo não estima sozinho a disponibilidade de uma janela maior ou a experiência de outra população.',
 '99,2% descreve esta população nesta janela; não é uma promessa para todas as situações.',section='Confiabilidade',widths=[.27,.73])
table('slo_sla','SLI, SLO e SLA: medida, objetivo e compromisso','A meta deve fazer sentido para quem usa o serviço', ['Termo','Significado','Exemplo didático'],[
 ['SLI','Indicador observado.','99,2% de chamadas boas na janela.'],['SLO','Objetivo para indicador e janela definidos.','Pelo menos 99% no período acordado.'],['SLA','Compromisso formal com condições próprias.','Nível acordado e consequências previstas.']],
 'O SLO não nasce de copiar um número popular. Depende do impacto, da viabilidade e da política da equipe. SLA é um compromisso formal, que pode ter condições e consequências; a aula não está criando um contrato jurídico. Um relatório de dez sondas locais não prova cumprimento de um SLO mensal. A meta fictícia de 99% serve para explicar o cálculo e a decisão, não para impor um padrão universal ao projeto.',
 'Medida observada, meta interna e compromisso formal são objetos diferentes.',section='Confiabilidade',widths=[.16,.42,.42])
slide('budget','Error budget: quanto da tolerância já foi consumido','Mesmo exemplo: 1000 chamadas • SLO 99% • 8 falhas',note=
 'No período encerrado, a tolerância de 1% de 1000 é dez chamadas. Oito falhas consumiram 80% desse orçamento; restaram duas, ou 20%. Se houver mais de dez falhas nessa população, a meta não foi atendida. Em uma janela viva, população e orçamento podem variar; este desenho não é um contador de falhas futuras autorizado indefinidamente. O efeito sobre releases depende de uma política acordada, não de punição automática. Priorizar correções pode reduzir o risco de continuar consumindo a tolerância.',
 takeaway='Orçamento permitido: 10 • consumido: 8 • restante: 2; a política define como isso orienta decisões.',kind='budget',section='Confiabilidade')
table('alerts','Alertas: condição, impacto e ação','Exemplos ilustrativos; calibrar janela e volume para o serviço', ['Alerta','Problema ou mérito','Melhoria / ação'],[
 ['CPU > 80% em uma amostra','Pode não representar falha percebida.','Relacionar a saturação e impacto; observar duração.'],['Erros aumentaram na operação','Sinal próximo do resultado do usuário.','Definir janela, amostra mínima e destino.'],['Dependência indisponível','Contexto útil, mas pode duplicar alertas.','Agrupar por incidente e consultar runbook.'],['Sonda sem dados','Não é sucesso nem falha medida da aplicação.','Investigar a coleta e o acesso ao destino.']],
 'Um alerta acionável diz o que mudou, em qual serviço, por quanto tempo e qual primeiro passo seguir. Nem toda métrica alta merece interromper alguém. Uma regra precisa tratar falta de dados, volume pequeno e ruído. Evite prometer que uma correlação automática elimina causas distintas. No laboratório a equipe observa a falha com comandos; não há envio automático de mensagens nem serviço de paging configurado.',
 'Alerta é um convite a agir com contexto, não apenas uma cor vermelha no painel.',section='Confiabilidade',widths=[.29,.35,.36])
slide('dashboard','Dashboard mínimo: quatro perguntas operacionais','Esboço didático • cada painel precisa de unidade, janela e contexto',note=
 'Explique o que se espera aprender ao olhar cada quadro. Tráfego ajuda a perceber ausência ou mudança de demanda; erros mostram resultados ruins; latência descreve o tempo; saturação mostra pressão sobre recursos. Nenhum número está representando medição real nesta figura. Registre versão e período para comparar antes/depois de uma entrega. Uma visualização bonita com denominador errado continua induzindo uma decisão errada. No projeto pequeno, uma tabela de medições bem definida pode cumprir o objetivo didático.',
 takeaway='Quatro sinais úteis: tráfego, erros, latência e saturação; associe-os à operação que importa.',kind='dashboard',section='Confiabilidade')
checkpoint('slo_check','Indicadores e decisões',[
 'Em 1000 chamadas, 992 boas e SLO 99%, quanto orçamento foi consumido?', 'Não houve chamadas. Podemos exibir 100% de sucesso?', '50 alertas por dia são ignorados. Basta desligar todos para resolver?'],[
 'A tolerância é 10 falhas. Oito foram consumidas: 80% do orçamento, restando duas nesta população.', 'Não. O denominador é zero: faltam observações. Indique ausência de amostra e confira a coleta.', 'Não. Priorize sinais ligados a impacto, agrupe duplicados e defina ação, dono e janela de cada regra.'], 'Confiabilidade')

flow('incident','Incidente: do impacto à recuperação e ao aprendizado','Sequência de resposta • algumas etapas ocorrem em paralelo', [('Detectar','Perceber o sintoma\nDelimitar o impacto'),('Investigar','Coletar evidências\nTestar hipóteses'),('Recuperar','Conter ou corrigir\nValidar a operação'),('Aprender','Registrar fatores\nPrevenir recorrência')],
 'Incidente é uma degradação que exige resposta coordenada, não toda mensagem error em um log. A prioridade pode ser mitigar o impacto antes de entender todos os fatores. Registre o que se sabe e o que ainda está em investigação. Coordenação e atualização das pessoas envolvidas podem ocorrer durante as etapas. No ensaio a falha é provocada em um projeto local de dados fictícios; a equipe não deve experimentar indisponibilidade em um serviço real sem contexto e autorização próprios.',
 'Restaurar o serviço e explicar a causa são objetivos relacionados; um não substitui o outro.',section='Diagnóstico')
slide('timeline','Linha do tempo: medir intervalos com definições','Exemplo fictício de um único incidente',note=
 'No exemplo, o impacto começa às 10:00, é detectado às 10:02 e o serviço é restaurado às 10:07. Tempo até detectar: dois minutos; do início à restauração: sete; da detecção à restauração: cinco. Especifique qual intervalo você está reportando. MTTD e MTTR costumam designar médias sobre vários eventos e MTTR tem expansões diferentes. Não chame um único intervalo de média nem confunda recuperação do serviço com conclusão de toda ação preventiva.',
 takeaway='Início → detecção: 2 min • início → restauração: 7 min • detecção → restauração: 5 min.',kind='timeline',section='Diagnóstico')
table('hypotheses','Sintoma, hipótese e causa confirmada','Exemplo: GET /visitas retorna 503', ['Etapa','O que dizer','Como sustentar'],[
 ['Sintoma','A consulta falhou para o cliente.','Status e corpo da chamada.'],['Hipótese','A dependência está indisponível.','Verificar estado do db e códigos de erro.'],['Teste','Recuperar a dependência no ensaio.','Repetir a mesma operação.'],['Conclusão','A parada do banco causou a falha provocada.','Linha do tempo, estado e teste após recuperação.']],
 'Uma hipótese não vira causa apenas por soar plausível ou ter sido gerada por IA. Use um teste que a diferencie de alternativas, como hostname errado, credencial ou schema ausente. No laboratório sabemos a intervenção feita e podemos observar sua reversão. Em produção, correlação temporal entre deploy e erro não prova por si só qual alteração foi responsável. Evite chamar todo problema de causa raiz única: fatores de detecção e resposta também podem ter contribuído.',
 'Uma causa confirmada explica as evidências e o efeito da intervenção, não só repete o sintoma.',section='Diagnóstico',widths=[.18,.40,.42])
slide('postmortem','Relatório sem culpa: transformar o incidente em melhoria','Contexto e decisões do sistema, sem procurar um culpado',[
 ('Descrever','Impacto, início e recuperação.\nEvidências e linha do tempo.\nO que era conhecido em cada decisão.'),('Explicar','Causa técnica e fatores contribuintes.\nO que funcionou e o que atrasou.\nLimites da investigação.'),('Melhorar','Ação concreta, responsável e prazo.\nComo verificar a melhoria.\nRunbook, teste ou alerta atualizado.')],
 'Sem culpa não significa sem responsabilidade. Significa investigar condições e decisões com as informações disponíveis, sem reduzir a explicação a erro humano. Uma ação como prestar mais atenção não muda o sistema de forma verificável. Compare com adicionar um teste funcional ao processo de promoção, com responsável e evidência de execução. O relatório deve reconhecer o que não foi confirmado e não preencher lacunas com uma narrativa convincente inventada.',
 'Uma boa prevenção tem mudança verificável, responsável e prazo; não apenas uma recomendação vaga.',section='Diagnóstico')

flow('demo_map','Demonstração: observar a mesma API em três momentos','Ambiente E6 separado dos projetos E4 e E5', [('Antes','Operação funciona\nColetar referência'),('Durante','Parar somente db\nObservar 503 e logs'),('Depois','Retomar db\nRepetir teste e conferir dados')],
 'A API ganha logs estruturados e métricas, mas continua usando PostgreSQL e o contador conhecido. O compose usa outro nome de projeto e outra porta, evitando misturar dados dos encontros anteriores. A sonda executa um número finito de chamadas e mostra status, conteúdo válido e tempo no cliente. A instrumentação é didática e manual, não uma instalação de OpenTelemetry. Traces permanecem conceituais; não afirmaremos capturá-los neste ensaio.',
 'A prova é a comparação da mesma operação antes, durante e após uma intervenção controlada.',section='Demonstração')
slide('demo_setup','Preparar o laboratório de observabilidade','Bash/zsh • Docker/Compose e Python 3 • porta 18086 livre',[
 ('Arquivo completo','Terminal na pasta do E6.\nBuild cria a API instrumentada.\nO banco usa dados fictícios.'),('Contratos','/health/live: processo HTTP.\n/health/ready: consulta básica.\n/visitas: operação de negócio.')],
 'Construa e teste antes da aula para antecipar downloads. Se outra cópia do projeto estiver ativa, escolha nome e porta exclusivos conforme o README. O script observar.py usa somente a biblioteca padrão do Python e não instala dependências. --wait aguarda os checks, mas não substitui a validação funcional. Guarde data, versão e nome do projeto para relacionar os resultados. Não execute comandos num diretório ou contexto que aponta para outro ambiente.',
 'A preparação identifica destino e versão antes de provocar qualquer falha.',kind='code',code='cd Práticas/encontro-6-observabilidade\ndocker compose config --quiet\ndocker compose up -d --build --wait\ncurl -fsS localhost:18086/version\npython3 observar.py --amostras 10',section='Demonstração',role='demo')
slide('demo_baseline','1. Capturar a referência e correlacionar uma chamada','Saídas reais variam: anote os valores observados',[
 ('Referência','POST incrementa o contador.\nAnote o total N.\nSonda deve ter 10 boas de 10.'),('Correlação','curl -i mostra X-Request-Id.\nLocalize o ID no log da API.\nCompare status e rota.')],
 'A requisição manual e a sonda são chamadas diferentes, cada uma com seu ID. O cabeçalho permite localizar exatamente uma resposta no log, não qualquer evento que ocorreu perto no tempo. O total depende de uso prévio do volume. Os tempos são medidos no ambiente atual e não devem ser substituídos pelos números ilustrativos dos slides. O arquivo de métrica acumula chamadas desde a partida e pode incluir leituras manuais além das dez sondas.',
 'Mesmo período e mesma população são necessários para comparar números.',kind='code',code='curl -fsS -X POST localhost:18086/visitas\ncurl -i localhost:18086/visitas\npython3 observar.py --amostras 10\ndocker compose logs --tail=40 app\ncurl -fsS localhost:18086/metrics',section='Demonstração',role='demo')
slide('demo_fault','2. Provocar uma falha na dependência','Somente no projeto local do laboratório',[
 ('O que muda','db fica parado.\nA API continua viva.\nA operação dependente falha.'),('Resultado esperado','/health/live: 200.\n/visitas: 503.\nSonda: 0 boas de 5.')],
 'stop mantém o container e os dados; não remove o volume. Espere que as consultas falhem e colete os sinais. O retorno exato de erro do driver pode variar entre conexão encerrada e recusada conforme o momento; não exija uma única string para reconhecer a dependência indisponível. O argumento esperado=503 diz ao script para confirmar a falha induzida: exit code zero nesse modo não quer dizer serviço saudável. Interprete o resumo, que continua registrando chamadas não boas.',
 'Processo vivo, healthcheck e função de negócio observam contratos diferentes.',kind='code',code='docker compose stop db\ncurl -i localhost:18086/health/live\ncurl -i localhost:18086/visitas\npython3 observar.py --amostras 5 --esperado 503\ndocker compose ps -a',section='Demonstração',role='demo')
slide('demo_evidence','3. Reunir evidência antes de decidir','Estado + evento + resultado funcional',[
 ('Estado','ps -a mostra db parado.\napp pode estar Up e depois unhealthy.'),('Evento e métrica','Log associa 503, rota e ID.\nCounter de falhas aumenta.\nA janela da sonda mostra impacto.')],
 'Identifique o último evento pertinente, pois o tail pode incluir sucessos anteriores e probes. Logs não contêm automaticamente toda a história: retenção e volume limitam o que está disponível. Métricas da API excluem as rotas de saúde e métricas; request_id não aparece como label. Leia a unidade do histograma: segundos, enquanto os logs e a sonda usam milissegundos. A hipótese banco parado é sustentada por estado e intervenção conhecida, não apenas por um número vermelho.',
 'A soma dos sinais deve sustentar a hipótese; guarde também o contexto e os limites da coleta.',kind='code',code='docker compose ps -a\ndocker compose logs --since=5m --tail=80 app\ncurl -fsS localhost:18086/metrics\n# No log: request_id, route, status, error_code\n# Nas métricas: método, rota, status e duração',section='Demonstração',role='demo')
slide('demo_recover','4. Recuperar e repetir o mesmo teste','O processo da API trata a indisponibilidade e aceita novas consultas',[
 ('Recuperar','start db retoma o banco.\nAguardar /health/ready.\nNão recriar app neste ensaio.'),('Validar','Sonda volta a 10 boas de 10.\nContador permanece N.\nNovos logs têm status 200.')],
 'O helper aguardar.py repete /health/ready com limite de tentativas; assim verifica a conexão a partir da API, inclusive a recuperação do pool. A prontidão não substitui o teste de /visitas. Se a espera falhar, investigar antes de iniciar a janela depois. Não use up --wait na stack toda só para recuperar o banco, pois pode alterar instâncias e confundir a comparação. O comportamento de recuperação depende do código desta API; não generalize para uma aplicação que encerra ao perder a dependência. Após retornar, registre também a ação preventiva.',
 'Recuperação comprovada = operação restaurada + dados conferidos + evidência registrada.',kind='code',code='docker compose start db\npython3 aguardar.py\n# Se a espera falhar, investigar antes de seguir.\npython3 observar.py --amostras 10\ncurl -fsS localhost:18086/visitas\ndocker compose logs --tail=30 app',section='Demonstração',role='demo')
table('demo_compare','Antes, durante e depois: interpretar sem misturar janelas','Exemplo de resultados esperados • tempos reais vêm da execução', ['Janela da sonda','Resultado','Conclusão'],[
 ['Antes: 10 chamadas','10 boas; 0 falhas.','Referência funcional observada.'],['Durante: 5 chamadas','0 boas; 5 falhas.','Dependência indisponível afetou a operação.'],['Depois: 10 chamadas','10 boas; 0 falhas.','Recuperação funcional observada.'],['Todo o ensaio: 25','20 / 25 = 80% boas.','Agregado mistura referência e falha deliberada.']],
 'O agregado de 80% está matematicamente correto para as 25 sondas, mas descreve um experimento de falha, não uma disponibilidade mensal. Chamadas manuais e healthchecks não entram nesse denominador da sonda. Os contadores da API podem mostrar outro total, porque registram chamadas manuais de /visitas também. Um teste com falha induzida não deve ser usado para comparar equipes por desempenho. Ele serve para demonstrar detecção, explicação e recuperação.',
 'Informe a janela e o propósito do ensaio; o mesmo conjunto de dados admite resumos com sentidos diferentes.',section='Demonstração',widths=[.30,.30,.40])
slide('slow_case','Caso resolvido: HTTP 200, mas o usuário espera demais','Cenário ilustrativo; atraso opcional reproduzível no README',[
 ('Sintoma','Sucesso por status continua alto.\nDuração da chamada aumenta.\nUsuário percebe lentidão.'),('Evidência','Compare cliente e servidor.\nVeja tempo da dependência.\nConfira configuração e versão.'),('Causa no ensaio','DEMO_DELAY_MS adiciona espera no código.\nRemover o atraso e repetir a sonda.\nNão atribuir automaticamente ao banco.')],
 'O atraso artificial é inserido no wrapper da consulta e aparece no campo dependency_ms. Esse campo mede a espera da aplicação ao redor da operação, não somente processamento SQL no servidor do banco. Por isso um tempo alto não prova banco lento. O exercício opcional recria app para aplicar a variável, o que zera contadores em memória. Compare novas janelas da sonda, sem subtrair counters de processos diferentes. Isso introduz a diferença entre sucesso e objetivo de latência.',
 'Uma operação pode estar disponível e ainda falhar no objetivo de tempo; medir apenas status deixa essa falha invisível.',section='Demonstração')
checkpoint('incident_check','Confirmar a recuperação',[
 'A sonda recebeu 503, mas app está Up. Há contradição?', 'Após recuperar, o counter de falhas continua em 5. O serviço ainda está falhando?', 'dependency_ms alto prova que o servidor do banco está lento?'],[
 'Não. O processo da API segue vivo enquanto a operação que usa db pode estar indisponível.', 'Não necessariamente. Counter acumula história. Observe a variação na nova janela e repita a operação.', 'Não. Inclui a espera medida pelo cliente da dependência; no ensaio opcional há atraso artificial no código.'], 'Demonstração')
slide('ai_use','IA na investigação: propor, confrontar e registrar','Retomar a governança do encontro 5',[
 ('Entrada útil','Sintoma, janela e versão.\nLogs mínimos sem segredos.\nO que já foi testado.'),('Saída esperada','Hipóteses com evidência.\nTeste que possa refutá-las.\nLimitações e próximo passo.'),('Decisão humana','Revisar comandos e impacto.\nExecutar teste controlado.\nRegistrar resultado e divergências.')],
 'A IA pode organizar um conjunto de eventos e sugerir hipóteses, mas uma explicação plausível não prova causalidade. Peça que diferencie fatos fornecidos de inferências. O aluno deve conseguir explicar por que aceitou ou rejeitou uma sugestão. Não enviar credenciais, dados pessoais ou dumps completos. Quando não houver autorização para usar um serviço externo, use dados sintéticos e faça a revisão em sala.',
 'A evidência vem do sistema e do teste; a resposta da IA é uma contribuição a revisar.',section='IA aplicada')
slide('ai_prompt','Exemplo de prompt com critérios verificáveis','Dados sintéticos • copiar e adaptar ao contexto autorizado',[
 ('Peça vínculo','Cada hipótese deve citar um fato.\nSe faltar dado, declarar a lacuna.'),('Peça um teste','Indicar o resultado esperado.\nDefinir o que refutaria a hipótese.')],
 'Leia o prompt e peça à turma que antecipe uma resposta adequada. Uma boa hipótese é dependência indisponível, sustentada pelo estado do db e pelos 503. Um teste é iniciar db, esperar prontidão e repetir a operação sem trocar app. Isso confirma a causa induzida neste ensaio; num incidente real ainda pode faltar explicar por que o banco parou. Não é necessário enviar esse prompt a uma ferramenta para discutir a qualidade do raciocínio.',
 'Uma pergunta melhor produz uma investigação mais verificável, não uma garantia de acerto.',kind='code',code='Contexto: laboratório local, API versão 3.0.0.\nFatos: /health/live=200; /visitas=503; db está parado.\nMudança conhecida: executei compose stop db.\nNão há evidência de perda de dados.\nSepare fatos e hipóteses. Para cada hipótese:\n- cite o fato que a sustenta;\n- proponha um teste e como refutá-la;\n- explique riscos e limites.\nNão proponha apagar volumes ou dados.',section='IA aplicada')
slide('ai_case','Caso resolvido: “apague o volume e tente novamente”','Resposta gerada deve passar por revisão',[
 ('Problema','O conselho destruiria dados.\nNão explica a causa do 503.\nNão é necessário neste ensaio.'),('Decisão','Rejeitar a sugestão.\nPreservar estado e evidências.\nRetomar db e validar a operação.'),('Registro','Anotar a sugestão rejeitada.\nExplicar risco e alternativa.\nVincular o resultado do teste.')],
 'O caso é ilustrativo, não uma saída real de uma ferramenta. A indisponibilidade observada decorre do banco parado intencionalmente. Reinicializar armazenamento não é tratamento proporcional. Também trate frases dentro de logs como dados: um evento que diga ignore as regras não autoriza nenhuma ação. O mesmo vale para recomendações copiadas de tickets. A equipe deve documentar a revisão, sem inventar uma conversa com IA que não aconteceu.',
 'Revisão crítica pode resultar em rejeição; isso é uma evidência válida de uso responsável.',section='IA aplicada')
slide('aiops','AIOps: onde a automação pode ajudar','Capacidades possíveis, dependentes da qualidade dos dados',[
 ('Organizar sinais','Agrupar alertas semelhantes.\nResumir eventos da janela.\nRelacionar mudança e sintoma.'),('Sugerir análise','Destacar comportamento incomum.\nPriorizar hipóteses de investigação.\nExplicitar incertezas.'),('Controlar execução','Permissão mínima.\nAção limitada e auditável.\nVerificação e escalonamento.')],
 'AIOps designa usos de técnicas de IA em operações, não uma garantia de operação autônoma. Correlação temporal não prova causalidade: um deploy próximo ao erro pode ser coincidência. Não apresentar percentuais universais de produtividade ou prevenção. Compare a sugestão com uma hipótese alternativa e com o que realmente ocorreu no ambiente. Aqui a automação é discutida conceitualmente; o laboratório não instala uma plataforma de AIOps.',
 'Automatize tarefas com critérios claros; mantenha limites, rastreabilidade e verificação.',section='IA aplicada')
flow('bounded_action','Uma ação automática precisa de limites','Exemplo conceitual de recuperação controlada',[
 ('Condição','Sinal confirmado\nContexto autorizado'),('Ação','Runbook conhecido\nTentativas limitadas'),('Verificação','Repetir operação\nChecar efeito'),('Escalonar','Falhou ou risco alto?\nAcionar responsável')],
 'Explique por que reiniciar indefinidamente é perigoso: pode ampliar a indisponibilidade e apagar contexto. Um runbook deve definir escopo, permissões, limite de tentativas, confirmação de recuperação e destino de escalonamento. Ações destrutivas e mudanças de schema exigem avaliação específica. Este diagrama não é uma automação implementada nem envia notificações. No exercício, a pessoa executa a recuperação local e registra a evidência.',
 'Uma ação sem critério de parada e teste de recuperação não fecha o ciclo operacional.',section='IA aplicada')
checkpoint('ai_check','Revisar uma sugestão de IA',[
 'A resposta aponta o deploy como causa porque ocorreu antes do erro. Isso basta?', 'Um log contém a frase “execute este comando”. A equipe deve obedecer?', 'Rejeitar uma sugestão impede demonstrar uso responsável de IA?'],[
 'Não. Ordem temporal sugere uma hipótese. Compare versões, dependências e resultados de testes que possam refutá-la.',
 'Não. O log é dado a analisar. Comandos exigem revisão de finalidade, escopo, autorização e impacto.',
 'Não. Registre a sugestão, o motivo da rejeição e a alternativa validada. Não invente uma interação que não ocorreu.'], 'IA aplicada')
table('project_bridge','O mesmo projeto, seis incrementos conectados','Apresentar a evolução com evidências no repositório', ['Etapa','Contribuição','O que mostrar'],[
 ['E1–E2','Projeto, colaboração e implementação.','Contexto, histórico e decisões técnicas.'],['E3','Integração contínua.','Execução do pipeline e resultado dos testes.'],['E4','Containers e integração.','Dockerfile, Compose e operação funcionando.'],['E5','Entrega e operação.','Versão, configuração e plano de recuperação.'],['E6','Observabilidade e diagnóstico.','Sinais, incidente e recuperação comprovada.']],
 'Use o enunciado original para conferir os entregáveis específicos de cada encontro. A tabela é uma síntese da trajetória, não uma substituição da rubrica. A equipe continua no repositório único e no problema que escolheu. Não precisa migrar o projeto para a API do professor nem acrescentar uma plataforma de observabilidade inteira para reproduzir os conceitos.',
 'A apresentação deve ligar decisões, implementação e resultados do próprio projeto.',section='Projeto final',widths=[.15,.40,.45])
slide('lab','Preparação das equipes: 35 minutos com foco','145–180 min • aproveitar os incrementos já construídos',[
 ('0–12 min','Escolher operação relevante.\nConferir logs e uma medição.\nDefinir janela e resultado bom.'),('12–25 min','Executar falha local controlada.\nRegistrar hipótese e intervenção.\nConfirmar recuperação e dados.'),('25–35 min','Organizar links das evidências.\nRevisar relato e participação.\nEnsaiar a fala de 5–7 minutos.')],
 'Os 35 minutos são preparação final, não tempo para construir tudo do zero. Oriente a aproveitar código e evidências dos encontros anteriores. Se uma falha não puder ser induzida com segurança no ambiente atual, use um ensaio local previamente registrado, identifique a data e explique a limitação. Não declarar como realizado um teste apenas planejado. Acompanhe as equipes por risco e bloqueio; não exigir que todas usem as mesmas ferramentas.',
 'A entrega é da equipe e está no repositório; a demonstração deve mostrar evidências verificáveis.',section='Projeto final',role='atividade')
table('incident_model','Exemplo preenchido de relato de incidente','Exemplo didático • horários ilustrativos, não resultados medidos', ['Campo','Preenchimento'],[
 ['Impacto e janela','10:00–10:07: consulta /visitas indisponível no ensaio local.'],['Evidências','5 sondas retornaram 503; db parado; logs ligados por request_id.'],['Causa do ensaio','Banco interrompido pelo comando deliberado compose stop db.'],['Recuperação','start db; prontidão confirmada; 10 sondas boas; contador preservado.'],['Ação e responsável','Equipe: adicionar teste de dependência ao runbook antes da entrega.']],
 'Diferencie o gatilho controlado da causa que seria investigada em produção. Se o banco tivesse parado inesperadamente, seria necessário descobrir a razão: recurso, operação humana, configuração ou outro evento. O relatório pode dizer causa ainda não confirmada quando essa for a verdade. Cada evidência deve ganhar caminho ou link real no repositório. Os horários aqui servem para ensinar a estrutura; substitua pelos da execução da equipe.',
 'Um relato útil permite reconstruir o raciocínio sem depender da memória de quem apresentou.',section='Projeto final',widths=[.27,.73])
table('rubric_a','Rubrica oficial: construção e integração','70% da avaliação • pesos preservados', ['Critério','Peso','Evidência que ajuda a explicar'],[
 ['Projeto','25%','Problema, solução implementada e decisões do grupo.'],['CI','25%','Pipeline executado, testes e tratamento de falhas.'],['Containers','20%','Empacotamento, integração e execução reproduzível.']],
 'Os três pesos somam 70%. Consulte a rubrica original para os descritores completos. O slide organiza evidências sem criar novos critérios ou avaliação individual. A apresentação curta não deve ocultar os entregáveis técnicos: deixe links diretos para o avaliador consultar.',
 'Mostre o que foi implementado e executado; uma configuração isolada não comprova seu resultado.',section='Projeto final',widths=[.25,.12,.63])
table('rubric_b','Rubrica oficial: entregar, diagnosticar e comunicar','30% da avaliação • total geral: 100%', ['Critério','Peso','Evidência que ajuda a explicar'],[
 ['Entrega e operação','15%','Versão, configuração, execução e recuperação planejada.'],['Diagnóstico','10%','Sintoma, hipótese, teste, causa e recuperação comprovada.'],['Apresentação','5%','Narrativa clara de 5–7 min com evidências do grupo.']],
 'Logs e métricas sustentam tanto a operação quanto o diagnóstico; não são um peso adicional. A avaliação permanece em grupo, conforme o enunciado. Não criar uma arguição com nota individual. Explique que mostrar o erro deliberado é positivo quando acompanhado por método, interpretação e recuperação. O resultado final não depende de esconder limitações.',
 'Os pesos continuam 25 / 25 / 20 / 15 / 10 / 5; observabilidade conecta as evidências.',section='Projeto final',widths=[.25,.12,.63])
slide('presentation','Roteiro de apresentação: exemplo de seis minutos','Dentro do intervalo oficial de 5–7 minutos por equipe',[
 ('0–2 min','0–1: problema e solução.\n1–2: CI e teste executado.\nUse links já abertos.'),('2–4 min','2–3: containers e integração.\n3–4: entrega e recuperação.\nMostre versão e configuração.'),('4–6 min','4–5: incidente e evidências.\n5–6: decisões, IA e limites.\nConcluir com aprendizado.')],
 'É um roteiro sugerido, não seis novos itens de nota. Distribua a participação de acordo com o trabalho do grupo. Não consuma toda a fala aguardando build ou download: tenha evidências previamente produzidas e identifique quando usar gravação ou captura. Uma operação curta ao vivo pode apoiar a explicação. Cada slot de oito minutos inclui fala de cinco a sete e transição ou feedback; respeitar o relógio protege as demais equipes.',
 'Selecione uma narrativa demonstrável: o problema, a entrega, a falha e o que a equipe aprendeu.',section='Projeto final')
slide('evidence_index','Organizar evidências para quem não acompanhou a aula','Modelo de índice no README do repositório da equipe',[
 ('Caminhos reais','Trocar exemplos pelos arquivos do grupo.\nPreferir links diretos e datas.'),('Contexto mínimo','Comando, versão, janela e resultado.\nCaptura sem contexto é ambígua.')],
 'O índice reduz o tempo gasto procurando arquivos durante a apresentação e a avaliação. Não versionar segredos ou logs contendo dados pessoais. Saídas de teste devem indicar a versão e a data. No registro de IA, distinguir sugestão, revisão e teste. Se a equipe não executou uma etapa, registrar como pendente em vez de inventar um resultado. Os nomes exibidos são apenas uma organização possível.',
 'A evidência deve ser localizável e interpretável, não apenas existir em uma pasta.',kind='code',code='README.md\ndocs/arquitetura.md\ndocs/entrega-e-recuperacao.md\ndocs/incidente.md\ndocs/uso-de-ia.md\nevidencias/ci/\nevidencias/containers/\nevidencias/antes.jsonl\nevidencias/durante.jsonl\nevidencias/depois.jsonl',section='Projeto final')
checkpoint('final_check','Defender as evidências do projeto',[
 'O grupo mostra apenas um dashboard verde. O diagnóstico está demonstrado?', 'Uma captura foi feita ontem. Pode entrar na apresentação?', 'O contador de falhas acumulado é diferente do total da sonda. Há necessariamente erro?'],[
 'Não. Explique operação, janela, sintoma, hipótese, teste, causa sustentada e recuperação. O painel é uma parte da evidência.',
 'Sim, se identificada como registro anterior, com data, versão e contexto. Não a apresentar como execução ao vivo.',
 'Não. Podem ter janelas e populações diferentes. A API inclui chamadas manuais; a sonda conta somente suas chamadas.'], 'Projeto final')
slide('closing','Fechamento: explicar o ciclo completo','Do problema ao aprendizado operacional',[
 ('Construir e integrar','Mudanças rastreáveis.\nTestes e pipeline.\nExecução em containers.'),('Entregar e observar','Configuração e versão.\nSinais com significado.\nObjetivos e recuperação.'),('Aprender e comunicar','Causa sustentada por evidência.\nAção de melhoria com responsável.\nRepositório e apresentação final.')],
 'Nos quatro minutos finais, confira os links e a submissão no prazo estabelecido: até o fim do encontro 6. Retome uma decisão que cada equipe agora consegue explicar melhor. Os próximos slides são consulta e não precisam ser expostos antes das apresentações. O fechamento não cria outra entrega. Reforce o percurso do mesmo projeto e o uso crítico de automação e IA.',
 'DevOps conecta colaboração, entrega e feedback; o projeto final deve tornar essa conexão visível.',section='Fechamento')
slide('consult_trace','Consulta | Request ID não é tracing distribuído','Como evoluir a instrumentação depois do laboratório',[
 ('Correlação local','Um ID liga resposta e log.\nAjuda a buscar uma requisição.\nNão cria spans automaticamente.'),('Trace distribuído','Contexto propagado entre serviços.\nSpans com início, fim e relação.\nInstrumentação e exportação.'),('Decisões','Escolher pontos de coleta.\nControlar dados e amostragem.\nVerificar custo e utilidade.')],
 'O laboratório usa somente request_id local; o diagrama de trace é conceitual. Para evoluir, a equipe pode estudar OpenTelemetry, contexto de trace e um backend adequado. A instrumentação precisa propagar contexto pelas chamadas relevantes. Amostragem reduz volume e pode deixar uma requisição fora do conjunto armazenado. Não prometer que todo evento estará disponível nem exigir essa evolução na entrega atual.',
 'Adote tracing quando a pergunta exigir relações entre operações; não apenas para acrescentar uma ferramenta.',section='Consulta',study_only=True)
slide('consult_cardinality','Consulta | O custo de colocar tudo em labels','Métricas agregadas e eventos detalhados precisam de escolhas diferentes',[
 ('Labels úteis','Método normalizado.\nRota conhecida.\nStatus HTTP.'),('Evitar sem controle','request_id único.\nURL com parâmetros livres.\nIdentidade de cada usuário.'),('Por quê?','Cada combinação cria uma série.\nMais séries elevam custo.\nDetalhes cabem em logs revisados.')],
 'Na API, as rotas desconhecidas são normalizadas e não entram nas métricas de /visitas. O ID aparece nos logs e no cabeçalho, não nas labels. A cardinalidade depende das combinações possíveis; se cada chamada ganha um valor novo, o conjunto cresce continuamente. Também definir retenção e acesso aos logs. Essa é uma escolha de projeto, não simplesmente remover dados sem compreender a pergunta de investigação.',
 'Colete o contexto necessário no lugar apropriado e limite dimensões sem controle.',section='Consulta',study_only=True)
slide('consult_histogram','Consulta | Ler os buckets de um histograma','No laboratório: duração no servidor em segundos; buckets cumulativos',[
 ('Exemplo didático','le="0.1": 8 chamadas.\nle="0.3": 10 chamadas.\n8 já estão contidas nas 10.'),('Interpretação','2 chamadas entre 0,1 e 0,3 s.\nNão somar todos os buckets.\n+Inf deve igualar _count.'),('Limitação','Faixas não guardam cada duração.\nPercentis são estimados.\nA sonda tem amostras do cliente.')],
 'O histograma do servidor cobre GET /visitas, incluindo respostas de erro, e exclui as rotas de saúde e métricas. Os números deste slide são ilustrativos. _sum dividido por _count fornece a média das observações acumuladas quando count é positivo; não fornece p95. A sonda calcula nearest-rank sobre durações individuais do cliente. Medições em locais diferentes não precisam coincidir. Reiniciar app zera todas as métricas locais.',
 'Unidade, população, janela e reinício precisam acompanhar qualquer cálculo.',section='Consulta',study_only=True)
slide('consult_slow','Consulta | Reproduzir a lentidão controlada','Opcional • executar somente no laboratório local',[
 ('Comparar','Nova janela: status e p95.\nDEMO_DELAY_MS adiciona espera.\nNão é falha real do PostgreSQL.'),('Restaurar','Voltar a zero e repetir a sonda.\nA recriação zera métricas locais.\nO volume do banco permanece.')],
 'Os comandos usam atribuição temporária de variável no shell, válida em Linux, macOS e WSL. O delay é aplicado ao wrapper da consulta e pode afetar a prontidão, mas 400 ms fica abaixo do timeout configurado. --no-deps recria apenas app. O teste demonstra que sucesso por status pode coexistir com latência ruim. O README oferece a sequência e exige confirmar a prontidão após a recriação. Não comparar counters antes e depois como se fossem do mesmo processo.',
 'A mesma operação precisa atender ao resultado esperado e ao objetivo de tempo definido.',kind='code',code='DEMO_DELAY_MS=400 docker compose up -d \\\n  --no-deps --force-recreate --wait app\npython3 observar.py --amostras 10\ncurl -fsS localhost:18086/version\nDEMO_DELAY_MS=0 docker compose up -d \\\n  --no-deps --force-recreate --wait app\npython3 observar.py --amostras 10',section='Consulta',study_only=True)

for i,d in enumerate(S,1):
 d['source_id']=i
 if d['role']=='pergunta':d['question']='\n'.join(d['questions'])
 if d['role']=='resposta':d['answer']='\n'.join(d['answers'])
REFS=[
 ('OpenTelemetry: sinais','https://opentelemetry.io/docs/concepts/signals/'),
 ('OpenTelemetry: observabilidade','https://opentelemetry.io/docs/concepts/observability-primer/'),
 ('OpenTelemetry: traces','https://opentelemetry.io/docs/concepts/signals/traces/'),
 ('Prometheus: tipos de métricas','https://prometheus.io/docs/concepts/metric_types/'),
 ('Prometheus: histogramas','https://prometheus.io/docs/practices/histograms/'),
 ('Prometheus: nomes e labels','https://prometheus.io/docs/practices/naming/'),
 ('Google SRE: monitoramento','https://sre.google/sre-book/monitoring-distributed-systems/'),
 ('Google SRE: implementação de SLOs','https://sre.google/workbook/implementing-slos/'),
 ('Google SRE: orçamento de erro','https://sre.google/workbook/error-budget-policy/'),
 ('Google SRE: alertas baseados em SLO','https://sre.google/workbook/alerting-on-slos/'),
 ('Google SRE: post-mortem','https://sre.google/sre-book/postmortem-culture/'),
 ('Docker Compose: serviços','https://docs.docker.com/reference/compose-file/services/'),
 ('OWASP: prompt injection','https://genai.owasp.org/llmrisk/llm01-prompt-injection/')]
